# Copyright (c) 2019 Ableton AG, Berlin. All rights reserved.

branches:
  only:
    - main

os: osx
osx_image: xcode12.2

env:
  - SDK=iphoneos CONFIGURATION=Debug
  - SDK=iphoneos CONFIGURATION=Release
  - SDK=iphonesimulator CONFIGURATION=Debug
  - SDK=iphonesimulator CONFIGURATION=Release

script:
  - xcodebuild -configuration $CONFIGURATION -sdk $SDK -alltargets CODE_SIGNING_ALLOWED="NO"
